--- name:default

####################################
### Motion planner configuration ###
####################################

# Timestamp when to reach the goal of the motion plan
time_horizon: 160

# Time resolution of the planner
time_step: 1.006289308

# Maximum number of iterations before considering failure
max_iterations: 200

# Threshold of the iteration control step to consider convergence
control_threshold: 0.001

# Linear searching step of the least-cost actuation each iteration
line_search_step: 0.30

# Shall the motion planner check for the distance to the goal to converge?
check_distance: true

# Shall the motion planner check for the orientation to the goal to converge?
check_orientation: true

# Shall the motion planner track a warmstarting base trajectory?
track_reference_trajectory: true

##############################################
### Model predictive control configuration ###
##############################################

# Admisible distance error (m) to the trajectory before replanning
threshold_distance_error: 0.05

# Time horizon (s) in which to start checking the goal pose error
threshold_time_goal_pose: 80

# Admisible distance error (m) of the goal pose before replanning
threshold_goal_distance_error: 0.01

# Admisible orientation error (rad) of the goal pose before replanning
threshold_goal_orientation_error: 0.5

# Admisible error in the position of a joint (rad) before replanning
threshold_position_error: 0.05

#########################
### Map configuration ###
#########################

# Obstacles map resolution
map_resolution: 0.05

# Path to the obstacles map file
obstacles_map_file: '../../../rover/data/maps/dummy_obstacles_map.txt'

#################################
### Robot model configuration ###
#################################

# Name of the robot model
robot_model_name: 'exoter'

#######################################
### Robot reading joints properties ###
#######################################

# Names of the manipulator joints
arm_joints_names: ['ARM_JOINT_1', 'ARM_JOINT_2', 'ARM_JOINT_3', 'ARM_JOINT_4', 'ARM_JOINT_5']

# Names of the left wheels driving joints
left_driving_joints_names: ['WHEEL_DRIVE_FL', 'WHEEL_DRIVE_CL', 'WHEEL_DRIVE_BL']

# Names of the right wheels driving joints
right_driving_joints_names: ['WHEEL_DRIVE_FR', 'WHEEL_DRIVE_CR', 'WHEEL_DRIVE_BR']

# Names of the left wheels steering joints
left_steering_joints_names: ['WHEEL_STEER_FL', 'WHEEL_STEER_BL']

# Names of the right wheels steering joints
right_steering_joints_names: ['WHEEL_STEER_FR', 'WHEEL_STEER_BR']

##########################################
### Robot commanding joints properties ###
##########################################

# Names of the robot arm joints commands
arm_commands_names: ['ARM_JOINT_1', 'ARM_JOINT_2', 'ARM_JOINT_3', 'ARM_JOINT_4', 'ARM_JOINT_5']

# Names of the robot base joints commands
base_commands_names: ['WHEEL_DRIVE_FL', 'WHEEL_DRIVE_FR', 'WHEEL_DRIVE_CL', 'WHEEL_DRIVE_CR', 'WHEEL_DRIVE_BL', 'WHEEL_DRIVE_BR', 'WHEEL_STEER_FL', 'WHEEL_STEER_FR', 'WHEEL_STEER_BL', 'WHEEL_STEER_BR', 'WHEEL_WALK_FL', 'WHEEL_WALK_FR', 'WHEEL_WALK_CL', 'WHEEL_WALK_CR', 'WHEEL_WALK_BL', 'WHEEL_WALK_BR', 'WHEEL_DRIVE_GROUP', 'WHEEL_STEER_GROUP', 'WHEEL_WALK_GROUP']

########################################
### Manipulator modelling properties ###
########################################

# Zero position of the manipulator joints DKM w.r.t. the real zero
arm_model_zero_position: [1.5707963267948966192, -1.5707963267948966192, 0, 1.5707963267948966192, 1.5707963267948966192]

# Positive movement direction of the model joints w.r.t. the real ones
arm_model_positive_direction: [-1, -1, -1, 1, 1]




--- name:exoter_ack

####################################
### Motion planner configuration ###
####################################

# Timestamp when to reach the goal of the motion plan
time_horizon: 160

# Time resolution of the planner
time_step: 0.8

# Maximum number of iterations before considering failure
max_iterations: 200

# Threshold of the iteration control step to consider convergence
control_threshold: 0.05

# Linear searching step of the least-cost actuation each iteration
line_search_step: 0.32

# Shall the motion planner check for the distance to the goal to converge?
check_distance: true

# Shall the motion planner check for the orientation to the goal to converge?
check_orientation: true

# Shall the motion planner track a warmstarting base trajectory?
track_reference_trajectory: true

##############################################
### Model predictive control configuration ###
##############################################

# Admisible distance error (m) to the trajectory before replanning
threshold_distance_error: 0.04

# Time horizon (s) in which to start checking the goal pose error
threshold_time_goal_pose: 120

# Admisible distance error (m) of the goal pose before replanning
threshold_goal_distance_error: 0.01

# Admisible orientation error (rad) of the goal pose before replanning
threshold_goal_orientation_error: 0.5

# Admisible error in the position of a joint (rad) before replanning
threshold_position_error: 0.02

#########################
### Map configuration ###
#########################

# Obstacles map resolution
map_resolution: 0.02

# Path to the obstacles map file
obstacles_map_file: '../../../rover/data/maps/prl/global_terrainMap_2cm.txt'

#################################
### Robot model configuration ###
#################################

# Name of the robot model
robot_model_name: 'exoter_ack'

#######################################
### Robot reading joints properties ###
#######################################

# Names of the manipulator joints
arm_joints_names: ['ARM_JOINT_1', 'ARM_JOINT_2', 'ARM_JOINT_3', 'ARM_JOINT_4', 'ARM_JOINT_5']

# Names of the left wheels driving joints
left_driving_joints_names: ['WHEEL_DRIVE_FL', 'WHEEL_DRIVE_CL', 'WHEEL_DRIVE_BL']

# Names of the right wheels driving joints
right_driving_joints_names: ['WHEEL_DRIVE_FR', 'WHEEL_DRIVE_CR', 'WHEEL_DRIVE_BR']

# Names of the left wheels steering joints
left_steering_joints_names: ['WHEEL_STEER_FL', 'WHEEL_STEER_BL']

# Names of the right wheels steering joints
right_steering_joints_names: ['WHEEL_STEER_FR', 'WHEEL_STEER_BR']

##########################################
### Robot commanding joints properties ###
##########################################

# Names of the robot arm joints commands
arm_commands_names: ['ARM_JOINT_1', 'ARM_JOINT_2', 'ARM_JOINT_3', 'ARM_JOINT_4', 'ARM_JOINT_5']

# Names of the robot base joints commands
base_commands_names: ['WHEEL_DRIVE_FL', 'WHEEL_DRIVE_FR', 'WHEEL_DRIVE_CL', 'WHEEL_DRIVE_CR', 'WHEEL_DRIVE_BL', 'WHEEL_DRIVE_BR', 'WHEEL_STEER_FL', 'WHEEL_STEER_FR', 'WHEEL_STEER_BL', 'WHEEL_STEER_BR', 'WHEEL_WALK_FL', 'WHEEL_WALK_FR', 'WHEEL_WALK_CL', 'WHEEL_WALK_CR', 'WHEEL_WALK_BL', 'WHEEL_WALK_BR', 'WHEEL_DRIVE_GROUP', 'WHEEL_STEER_GROUP', 'WHEEL_WALK_GROUP']

########################################
### Manipulator modelling properties ###
########################################

# Zero position of the manipulator joints DKM w.r.t. the real zero
arm_model_zero_position: [1.5707963267948966192, -1.5707963267948966192, 0, 1.5707963267948966192, 1.5707963267948966192]

# Positive movement direction of the model joints w.r.t. the real ones
arm_model_positive_direction: [-1, -1, -1, 1, 1]





--- name:exoter_ack_test

####################################
### Motion planner configuration ###
####################################

# Timestamp when to reach the goal of the motion plan
time_horizon: 160

# Time resolution of the planner
time_step: 1.006289308

# Maximum number of iterations before considering failure
max_iterations: 200

# Threshold of the iteration control step to consider convergence
control_threshold: 0.05

# Linear searching step of the least-cost actuation each iteration
line_search_step: 0.32

# Shall the motion planner check for the distance to the goal to converge?
check_distance: true

# Shall the motion planner check for the orientation to the goal to converge?
check_orientation: true

# Shall the motion planner track a warmstarting base trajectory?
track_reference_trajectory: true

##############################################
### Model predictive control configuration ###
##############################################

# Admisible distance error (m) to the trajectory before replanning
threshold_distance_error: 0.10

# Time horizon (s) in which to start checking the goal pose error
threshold_time_goal_pose: 80

# Admisible distance error (m) of the goal pose before replanning
threshold_goal_distance_error: 0.01

# Admisible orientation error (rad) of the goal pose before replanning
threshold_goal_orientation_error: 0.5

# Admisible error in the position of a joint (rad) before replanning
threshold_position_error: 0.05

#########################
### Map configuration ###
#########################

# Obstacles map resolution
map_resolution: 0.05

# Path to the obstacles map file
obstacles_map_file: '../../../rover/data/maps/dummy_obstacles_map.txt'

#################################
### Robot model configuration ###
#################################

# Name of the robot model
robot_model_name: 'exoter_ack'

#######################################
### Robot reading joints properties ###
#######################################

# Names of the manipulator joints
arm_joints_names: ['ARM_JOINT_1', 'ARM_JOINT_2', 'ARM_JOINT_3', 'ARM_JOINT_4', 'ARM_JOINT_5']

# Names of the left wheels driving joints
left_driving_joints_names: ['WHEEL_DRIVE_FL', 'WHEEL_DRIVE_CL', 'WHEEL_DRIVE_BL']

# Names of the right wheels driving joints
right_driving_joints_names: ['WHEEL_DRIVE_FR', 'WHEEL_DRIVE_CR', 'WHEEL_DRIVE_BR']

# Names of the left wheels steering joints
left_steering_joints_names: ['WHEEL_STEER_FL', 'WHEEL_STEER_BL']

# Names of the right wheels steering joints
right_steering_joints_names: ['WHEEL_STEER_FR', 'WHEEL_STEER_BR']

##########################################
### Robot commanding joints properties ###
##########################################

# Names of the robot arm joints commands
arm_commands_names: ['ARM_JOINT_1', 'ARM_JOINT_2', 'ARM_JOINT_3', 'ARM_JOINT_4', 'ARM_JOINT_5']

# Names of the robot base joints commands
base_commands_names: ['WHEEL_DRIVE_FL', 'WHEEL_DRIVE_FR', 'WHEEL_DRIVE_CL', 'WHEEL_DRIVE_CR', 'WHEEL_DRIVE_BL', 'WHEEL_DRIVE_BR', 'WHEEL_STEER_FL', 'WHEEL_STEER_FR', 'WHEEL_STEER_BL', 'WHEEL_STEER_BR', 'WHEEL_WALK_FL', 'WHEEL_WALK_FR', 'WHEEL_WALK_CL', 'WHEEL_WALK_CR', 'WHEEL_WALK_BL', 'WHEEL_WALK_BR', 'WHEEL_DRIVE_GROUP', 'WHEEL_STEER_GROUP', 'WHEEL_WALK_GROUP']

########################################
### Manipulator modelling properties ###
########################################

# Zero position of the manipulator joints DKM w.r.t. the real zero
arm_model_zero_position: [1.5707963267948966192, -1.5707963267948966192, 0, 1.5707963267948966192, 1.5707963267948966192]

# Positive movement direction of the model joints w.r.t. the real ones
arm_model_positive_direction: [-1, -1, -1, 1, 1]




--- name:exoter_diff

####################################
### Motion planner configuration ###
####################################

# Timestamp when to reach the goal of the motion plan
time_horizon: 160

# Time resolution of the planner
time_step: 1.006289308

# Maximum number of iterations before considering failure
max_iterations: 100

# Threshold of the iteration control step to consider convergence
control_threshold: 0.05

# Linear searching step of the least-cost actuation each iteration
line_search_step: 0.32

# Shall the motion planner check for the distance to the goal to converge?
check_distance: true

# Shall the motion planner check for the orientation to the goal to converge?
check_orientation: true

# Shall the motion planner track a warmstarting base trajectory?
track_reference_trajectory: true

##############################################
### Model predictive control configuration ###
##############################################

# Admisible distance error (m) to the trajectory before replanning
threshold_distance_error: 0.10

# Time horizon (s) in which to start checking the goal pose error
threshold_time_goal_pose: 80

# Admisible distance error (m) of the goal pose before replanning
threshold_goal_distance_error: 0.01

# Admisible orientation error (rad) of the goal pose before replanning
threshold_goal_orientation_error: 0.5

# Admisible error in the position of a joint (rad) before replanning
threshold_position_error: 0.05

#########################
### Map configuration ###
#########################

# Obstacles map resolution
map_resolution: 0.05

# Path to the obstacles map file
obstacles_map_file: '../../../rover/data/maps/dummy_obstacles_map.txt'

#################################
### Robot model configuration ###
#################################

# Name of the robot model
robot_model_name: 'exoter'

#######################################
### Robot reading joints properties ###
#######################################

# Names of the manipulator joints
arm_joints_names: ['ARM_JOINT_1', 'ARM_JOINT_2', 'ARM_JOINT_3', 'ARM_JOINT_4', 'ARM_JOINT_5']

# Names of the left wheels driving joints
left_driving_joints_names: ['WHEEL_DRIVE_FL', 'WHEEL_DRIVE_CL', 'WHEEL_DRIVE_BL']

# Names of the right wheels driving joints
right_driving_joints_names: ['WHEEL_DRIVE_FR', 'WHEEL_DRIVE_CR', 'WHEEL_DRIVE_BR']

# Names of the left wheels steering joints
left_steering_joints_names: ['WHEEL_STEER_FL', 'WHEEL_STEER_BL']

# Names of the right wheels steering joints
right_steering_joints_names: ['WHEEL_STEER_FR', 'WHEEL_STEER_BR']

##########################################
### Robot commanding joints properties ###
##########################################

# Names of the robot arm joints commands
arm_commands_names: ['ARM_JOINT_1', 'ARM_JOINT_2', 'ARM_JOINT_3', 'ARM_JOINT_4', 'ARM_JOINT_5']

# Names of the robot base joints commands
base_commands_names: ['WHEEL_DRIVE_FL', 'WHEEL_DRIVE_FR', 'WHEEL_DRIVE_CL', 'WHEEL_DRIVE_CR', 'WHEEL_DRIVE_BL', 'WHEEL_DRIVE_BR', 'WHEEL_STEER_FL', 'WHEEL_STEER_FR', 'WHEEL_STEER_BL', 'WHEEL_STEER_BR', 'WHEEL_WALK_FL', 'WHEEL_WALK_FR', 'WHEEL_WALK_CL', 'WHEEL_WALK_CR', 'WHEEL_WALK_BL', 'WHEEL_WALK_BR', 'WHEEL_DRIVE_GROUP', 'WHEEL_STEER_GROUP', 'WHEEL_WALK_GROUP']

########################################
### Manipulator modelling properties ###
########################################

# Zero position of the manipulator joints DKM w.r.t. the real zero
arm_model_zero_position: [1.5707963267948966192, -1.5707963267948966192, 0, 1.5707963267948966192, 1.5707963267948966192]

# Positive movement direction of the model joints w.r.t. the real ones
arm_model_positive_direction: [-1, -1, -1, 1, 1]

